name: CD - Frontend Deploy

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Frontend Deploy
        run: curl -X POST ${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK }}